SELECT TRANSACTION_ID,TRANSACTION_DATE,WAREHOUSE_ID,LOCATION_ID,CUST_ORDER_ID,CUST_ORDER_LINE_NO,PART_ID,
        (SELECT DESCRIPTION FROM PART WHERE ID = PART_ID) [DESCRIPTION],TYPE,CLASS,QTY,ACT_MATERIAL_COST,ACT_LABOR_COST,ACT_BURDEN_COST,ACT_SERVICE_COST
   FROM INVENTORY_TRANS WHERE TRANSACTION_DATE BETWEEN '20170901' AND '20170930' AND TYPE = 'O' AND CLASS = 'I' AND CUST_ORDER_ID IS NOT NULL
