SELECT R.CUSTOMER_ID,C.[NAME],R.SALESREP_ID,S.[NAME] [CONSULTOR],R.CURRENCY_ID,RI.INVOICE_ID,
       CASE WHEN R.INVOICE_ID LIKE 'RC%' THEN 'FACTURA ADELANTO' ELSE R.TERMS_DESCRIPTION END [CONDICION PAGO],
       ATC.TIPO,APTC.DESCRIPCION,ATC.TERMS_ID,AT.TERMS_ID,
       R.CREATE_DATE,R.INVOICE_DATE,RI.DUE_DATE,ACC.FECHA_VTO_ORIGINAL,RI.TOTAL_AMOUNT,RI.PAID_AMOUNT,RI.LAST_PAID_DATE,
       CASE WHEN CONVERT(DATETIME,CAST(CAST(RB.BITS AS VARBINARY(25)) AS VARCHAR(25)),105) IS NULL THEN R.INVOICE_DATE 
            ELSE CONVERT(DATETIME,CAST(CAST(RB.BITS AS VARBINARY(25)) AS VARCHAR(25)),105) END [RECEPCION CLIENTE], 
       CASE WHEN CONVERT(DATETIME,CAST(CAST(RB.BITS AS VARBINARY(25)) AS VARCHAR(25)),105) IS NULL THEN 'FECHA SISTEMA' 
            ELSE 'FECHA CLIENTE' END [FLAG RECEPCION CLIENTE],
       CASE WHEN R.INVOICE_DATE >  CONVERT(DATETIME,CAST(CAST(RB.BITS AS VARBINARY(25)) AS VARCHAR(25)),105) THEN 0 ELSE 1 END [VALIDACION],
       CASE WHEN (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 < 31) AND (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 > 0) THEN DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 ELSE 0 END [0 - 30 DIAS],
       CASE WHEN (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 > 31) AND (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 < 61) THEN DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 ELSE 0 END [31 - 60 DIAS],
       CASE WHEN (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 > 61) AND (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 < 91) THEN DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 ELSE 0 END [61 - 90 DIAS],
       CASE WHEN (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 > 91) AND (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 < 121) THEN DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 ELSE 0 END [91 - 120 DIAS],
       CASE WHEN (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 > 120) AND (DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 > 0) THEN DATEDIFF(DAY,GETDATE(),ACC.FECHA_VTO_ORIGINAL)*-1 ELSE 0 END [120 DIAS A MÁS]
  FROM RECEIVABLE_INST RI LEFT JOIN RECEIVABLE R ON RI.INVOICE_ID = R.INVOICE_ID
                          LEFT JOIN CUSTOMER C ON R.CUSTOMER_ID = C.ID
                          LEFT JOIN RECEIVABLE_BINARY RB ON RB.INVOICE_ID = R.INVOICE_ID
                          LEFT JOIN SALES_REP S ON R.SALESREP_ID = S.ID
                          LEFT JOIN ARG_CUOTAS_CC ACC ON ACC.INVOICE_ID = R.INVOICE_ID
                          LEFT JOIN ARG_TIPO_CC ATC ON ATC.INVOICE_ID = R.INVOICE_ID
                          LEFT JOIN ARG_PARAM_TIPO_CC APTC ON ATC.TIPO = APTC.TIPO
                          LEFT JOIN ARG_TERMS AT ON ATC.TERMS_ID = AT.TERMS_ID
 WHERE RI.TOTAL_AMOUNT <> RI.PAID_AMOUNT
 ORDER BY R.CREATE_DATE
 
SELECT * FROM ARG_CUOTAS_CC
SELECT * FROM ARG_PARAM_TIPO_CC
SELECT * FROM ARG_TIPO_CC WHERE INVOICE_ID = 'F001-001456'
SELECT * FROM ARG_TERMS
SELECT * FROM RECEIVABLE WHERE INVOICE_ID = 'F001-001456'
SELECT * FROM RECEIVABLE_BINARY WHERE INVOICE_ID = 'F001-001456'
SELECT * FROM RECEIVABLE_DIST WHERE INVOICE_ID = 'F001-001456'
CONVERT(varchar(25),miimagen,2), miimagen

SELECT CONVERT(DATETIME,CAST(CAST(BITS AS VARBINARY(25)) AS VARCHAR(25)),105) FROM RECEIVABLE_BINARY WHERE INVOICE_ID = 'F001-001456'